# docker-compose.yml
version: '3'

networks:
  LAN:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/24
services:
  user1:
    build: ./lan/user1
    networks:
      LAN:
        ipv4_address: 172.20.1.10
    tty: true
    container_name: user1
    hostname: user1
    dns: 172.20.1.2
  user2:
    build: ./lan/user2
    networks:
      LAN:
        ipv4_address: 172.20.1.11
    tty: true
    container_name: user2
    hostname: user2
    dns: 172.20.1.2
  intranet:
    build: ./lan/intranet
    networks:
      LAN:
        ipv4_address: 172.20.1.4
    tty: true
    container_name: intranet
    hostname: intranet
    dns: 172.20.1.2
  resolver:
    build: ./lan/resolver
    networks:
      LAN:
        ipv4_address: 172.20.1.2
    tty: true
    container_name: resolver
    hostname: resolver
    dns: 172.20.1.2
  soa:
    build: ./lan/soa
    networks:
      LAN:
        ipv4_address: 172.20.1.3
    tty: true
    container_name: soa
    hostname: soa
  mail:
    build: ./lan/mail
    networks:
      LAN:
        ipv4_address: 172.20.1.5
    tty: true
    container_name: mail
    hostname: mail
    dns: 172.20.1.2
    ports:
      - "25:25"
      - "465:465"
      - "143:143"
      - "993:993"
    environment:
      - maildomain=woodytoys.lab
    volumes:
      - /path_for_postfix_mail_delivery:/var/mail
      - /path_for_imap_storage:/home
    restart: always
  db:
    build: ./lan/db
    networks:
      LAN:
        ipv4_address: 172.20.1.6
    tty: true
    container_name: db
    volumes:
      - stockagedb:/var/lib/mysql

volumes:
  stockagedb:
