FROM mysql:latest
ENV MYSQL_ROOT_PASSWORD ephec
ENV MYSQL_DATABASE products
ENV MYSQL_USER dom
ENV MYSQL_PASSWORD cisco
#ADD lefchier.sql /docker-entrypoint-initdb.d
EXPOSE 3306
#RUN chmod 755 /var/lib/mysql
